"""add fee_records and attendance_records tables

Revision ID: 851a60e35d84
Revises: 2d2e369dccb7
Create Date: 2026-08-28 09:23:23.125930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851a60e35d84'
down_revision: Union[str, Sequence[str], None] = '2d2e369dccb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_section', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', name='attendance_status'), nullable=False),
    sa.Column('marked_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_class_section'), 'attendance_records', ['class_section'], unique=False)
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('fee_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'overdue', name='fee_payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_records_student_id'), 'fee_records', ['student_id'], unique=False)
    op.alter_column('announcements', 'posted_by',
               existing_type=sa.VARCHAR(length=266),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'posted_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=266),
               existing_nullable=False)
    op.drop_index(op.f('ix_fee_records_student_id'), table_name='fee_records')
    op.drop_table('fee_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_class_section'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
