"""add grading fields to homework submissions

Revision ID: 88c1537528f3
Revises: efdeec24077b
Create Date: 2026-08-11 18:50:53.372904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c1537528f3'
down_revision: Union[str, Sequence[str], None] = 'efdeec24077b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_submissions', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('homework_submissions', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('homework_submissions', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('homework_submissions', sa.Column('graded_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'homework_submissions', 'users', ['graded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.drop_column('homework_submissions', 'graded_by')
    op.drop_column('homework_submissions', 'feedback')
    op.drop_column('homework_submissions', 'max_score')
    op.drop_column('homework_submissions', 'score')
    # ### end Alembic commands ###
