"""add name to users and contact fields to student profiles

Revision ID: 95aa2b163349
Revises: 7cb17547e10e
Create Date: 2026-08-12 10:53:18.412438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95aa2b163349'
down_revision: Union[str, Sequence[str], None] = '7cb17547e10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('address', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('student_profiles', 'guardian_phone')
    op.drop_column('student_profiles', 'guardian_name')
    op.drop_column('student_profiles', 'address')
    op.drop_column('student_profiles', 'phone')
    # ### end Alembic commands ###
